# Generated by Django 3.1.7 on 2021-04-03 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2017, 5, 4)),
            preserve_default=False,
        ),
    ]
