// actions
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const UPDATE_EXPENSES = 'UPDATE_EXPENSES';
export const UPDATE_INCOMES = 'UPDATE_INCOMES';
export const UPDATE_LOADING = 'UPDATE_LOADING';

